INSERT INTO SELLER(ID, FIRST_NAME, LAST_NAME, STREET_ADDRESS, CITY, STATE, ZIP, PARENT_NAMES, CLUB, VERSION) 
VALUES 
(1, 'THAD', 'CRAFT', '15326 MOUNTAIN VW.', 'HEYWORTH', 'ILLINOIS', '61745', 'SHIRLEY FRASURE', 'LUCKY TRAILS', 1),
(2, 'SARAH', 'CRAFT', '15326 MOUNTAIN VW.', 'HEYWORTH', 'ILLINOIS', '61745', 'MARILYN AND LARRY WICKERT', 'LUCKY TRAILS', 1),
(3, 'JULIA', 'WICKERT', '1440 W. SR 10', 'NORTH JUDSON', 'INDIANA', '46366', 'MARILYN AND LARRY WICKERT', 'LUCKY TRAILS', 1),
(4, 'KIM', 'TEMPLE', '1234 MAIN ST.', 'KNOX', 'INDIANA', '46532', 'MR. AND MRS. TEMPLE', 'LUCKY TRAILS', 1);
